# Generated by Django 5.1.3 on 2024-12-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='orders/pdfs/%Y/%m/%d/')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('order_date', models.DateField()),
                ('shipping_method', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('total_items', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.batchorder')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/images/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.orderdetail')),
            ],
        ),
    ]
