# Generated by Django 5.1.3 on 2025-01-06 19:05

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_image',
            field=models.FilePathField(blank=True, max_length=500, null=True, path=pathlib.PureWindowsPath('C:/inkteo/media'), recursive=True),
        ),
    ]
