# Generated by Django 5.1.3 on 2025-01-07 17:46

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='pdf_file',
            field=models.FileField(upload_to=dashboard.models.pdf_file_upload_path),
        ),
    ]
