<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-01-07 23:32
=======
# Generated by Django 5.1.3 on 2025-01-07 21:26
>>>>>>> 9df032bef5d97a8d6078ead9ca087434a48ae28f

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_batchorder_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printimagesettings',
            name='dropbox_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printimagesettings',
            name='dropbox_folder_path',
            field=models.CharField(blank=True, default='/Print Images', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printimagesettings',
            name='dropbox_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printimagesettings',
            name='dropbox_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printimagesettings',
            name='use_dropbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printimagesettings',
            name='print_folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printimagesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
