# Generated by Django 5.1.3 on 2025-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_orderitem_print_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/images/'),
        ),
    ]
