# Generated by Django 5.1.3 on 2025-01-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_orderitem_image_remove_orderitem_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etsy_order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('order_date', models.DateField()),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_url', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.orderbatch')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
