# Generated by Django 5.1.3 on 2025-01-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_printimagesettings_dropbox_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printimagesettings',
            name='dropbox_folder_path',
        ),
    ]
