# Generated by Django 5.1.3 on 2025-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_orderitem_print_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
