# Generated by Django 5.1.3 on 2024-01-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_create_printimagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ] 